CREATE TABLE REGISTAALTERACOESPRECOS (
    NOME_COMERCIAL   VARCHAR2(200),
    CODIGO_REGISTRO  NUMBER,
    PRECO_ANTIGO      NUMBER(8,2),
    PRECO_NOVO        NUMBER(8,2),
    DATA_ALTERACAO    DATE
);